export const LANGUAGE = {
    resume: 'resume',
    home: 'home',
    about: 'about',
    projects: 'projects',
    contract: 'contract',
    full_name: 'full_name',
    skill: 'skill',
    work_exp: 'work_exp',
    mern_developer: 'mern_developer',
    home_1: 'home_1',
    home_2: 'home_2',
    home_3: 'home_3',
    about_title: 'about_title',
    about_bio: 'about_bio',
    about_bio_1: 'about_bio_1',
    about_bio_2: 'about_bio_2',
    about_bio_3: 'about_bio_3',
    about_bio_company: 'about_bio_company',
    about_bio_off_code: 'about_bio_off_code',
    about_work_exp_1: 'about_work_exp_1',
    about_work_exp_2: 'about_work_exp_2',   
}
//cắt chuỗi thành mảng các phần tử dựa trên ký tự xuống dòng (\n) hoặc ký tự xuống dòng (\r). Ký tự + trong biểu thức chính quy đại diện cho việc tìm kiếm một hoặc nhiều ký tự xuống dòng liên tiếp.
export const SPLIT_STRING = /[\n\r]+/
