export const LANGUAGE_DESCRIPTION = {
    resume: 'resume',
    home: 'home',
    about: 'about',
    projects: 'projects',
    contract: 'contract',
    full_name: 'full_name',
    skill: 'skill',
    work_experience: 'work_experience',
    mern_developer: 'mern_developer',
    home_description_1: 'home_description_1',
    home_description_2: 'home_description_2',
    home_description_3: 'home_description_3',
    about_title: 'about_title',
    about_biography: 'about_biography',
    about_biography_description_1: 'about_biography_description_1',
    about_biography_description_2: 'about_biography_description_2',
    about_biography_description_3: 'about_biography_description_3',
    about_biography_at_the_company: 'about_biography_at_the_company',
    about_biography_off_code: 'about_biography_off_code',
    about_work_experience_plan_1: 'about_work_experience_plan_1',
    about_work_experience_plan_2: 'about_work_experience_plan_2',   
}
//cắt chuỗi thành mảng các phần tử dựa trên ký tự xuống dòng (\n) hoặc ký tự xuống dòng (\r). Ký tự + trong biểu thức chính quy đại diện cho việc tìm kiếm một hoặc nhiều ký tự xuống dòng liên tiếp.
export const SPLIT_STRING = /[\n\r]+/
